apiVersion: v1
kind: Secret
metadata:
  name: lambrk-backend-secrets
type: Opaque
stringData:
  DB_USERNAME: "reddit_user"
  DB_PASSWORD: "reddit_password"
  JWT_SECRET: "your-jwt-secret-here-min-256-bits"
  MAIL_USERNAME: "noreply@reddit.com"
  MAIL_PASSWORD: "your-mail-password"
  OPENAI_API_KEY: "your-openai-api-key"
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
